### ISSUE TITLE
Cartesian DRO tile copy to clip board options drop down doesn't work

### ISSUE THREAD

**Issue by deeegee** [glowbuzzer/gbr#4] opened 2022-06-27 13:24 UTC
With the Cartesian DRO tile the drop-down giving options for the different copy to clipboard data items doesn't drop down.

Config - config_generic.json
UI - generic

(it does appear to work on the glowsite tiles documentation page)

**Comment by jugglingcats** [comment] 2022-06-28 17:37
Duplicate of #5

**Closed** 2022-06-28 17:38 UTC
Labels: bug, duplicate
